const e=JSON.parse('{"key":"v-7f4a0796","path":"/exception/gailan.html","title":"一文彻底搞懂Java异常处理，YYDS","lang":"zh-CN","frontmatter":{"title":"一文彻底搞懂Java异常处理，YYDS","shortTitle":"一文彻底搞懂Java异常处理","category":["Java核心"],"tag":["异常处理"],"description":"架构师进阶之路，小白的零基础Java教程，从入门到进阶，一文彻底搞懂Java异常处理，YYDS","head":[["meta",{"name":"keywords","content":"Java,Java SE,Java基础,Java教程,架构师进阶之路,Java入门,教程,java,异常处理"}],["meta",{"property":"og:url","content":"https://tobebetterjavaer.com/exception/gailan.html"}],["meta",{"property":"og:site_name","content":"架构师进阶之路"}],["meta",{"property":"og:title","content":"一文彻底搞懂Java异常处理，YYDS"}],["meta",{"property":"og:description","content":"架构师进阶之路，小白的零基础Java教程，从入门到进阶，一文彻底搞懂Java异常处理，YYDS"}],["meta",{"property":"og:type","content":"article"}],["meta",{"property":"og:updated_time","content":"2022-11-21T09:10:55.000Z"}],["meta",{"property":"og:locale","content":"zh-CN"}],["meta",{"property":"article:tag","content":"异常处理"}],["meta",{"property":"article:modified_time","content":"2022-11-21T09:10:55.000Z"}]]},"excerpt":"","headers":[{"level":2,"title":"一、什么是异常","slug":"一、什么是异常","link":"#一、什么是异常","children":[]},{"level":2,"title":"二、Exception和Error的区别","slug":"二、exception和error的区别","link":"#二、exception和error的区别","children":[]},{"level":2,"title":"三、checked和unchecked异常","slug":"三、checked和unchecked异常","link":"#三、checked和unchecked异常","children":[]},{"level":2,"title":"四、关于 throw 和 throws","slug":"四、关于-throw-和-throws","link":"#四、关于-throw-和-throws","children":[]},{"level":2,"title":"五、关于 try-catch-finally","slug":"五、关于-try-catch-finally","link":"#五、关于-try-catch-finally","children":[]}],"git":{"createdTime":1669017288000,"updatedTime":1669021855000,"contributors":[{"name":"Kong Ming(空明)","email":"token01@126.com","commits":2}]},"readingTime":{"minutes":14.89,"words":4468},"filePathRelative":"exception/gailan.md","localizedDate":"2022年11月21日"}');export{e as data};
